
CREATE TABLE Pagamentos (
    PagamentoID INT PRIMARY KEY AUTO_INCREMENT,
    PedidoID INT,
    MetodoPagamento VARCHAR(50) NOT NULL,
    Valor DECIMAL(10, 2) NOT NULL,
    DataPagamento DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PedidoID) REFERENCES Pedidos(PedidoID)
);
